// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wlight/lebron/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/homebanner/:id",
				Handler: HomebannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/flashsale",
				Handler: FlashSaleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recommend/:id",
				Handler: RecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/category/list",
				Handler: CategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart/list",
				Handler: CartListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/:id/comment",
				Handler: ProductCommentHandler(serverCtx),
			},
		},
	)
}
