// Code generated by goctl. DO NOT EDIT.
package types

type RecommendRequest struct {
	Cursor int64 `json:"cursor"`
	Ps     int64 `form:"ps,default=20"` // 每页大小
}

type RecommendResponse struct {
	Products      []*Product `json:"products"`
	IsEnd         bool       `json:"is_end"`         // 是否最后一页
	RecommendTime int64      `json:"recommend_time"` // 商品列表最后一个商品的推荐时间
}

type Product struct {
	ID          int64   `json:"id"`          // 商品id
	Name        string  `json:"name"`        // 商品名称
	Description string  `json:"description"` // 商品描述
	Price       float64 `json:"price"`       // 商品价格
	Stock       int64   `json:"stock"`       // 库存
	Category    string  `json:"category"`    // 分类
	Status      int64   `json:"status"`      // 状态：1-正常，2-下架
	CreateTime  int64   `json:"create_time"` // 创建时间
	UpdateTime  int64   `json:"update_time"` // 更新时间
}

type FlashSaleResponse struct {
	StartTime int64      `json:"start_time"` // 抢购开始时间
	Products  []*Product `json:"products"`
}

type CategoryListRequest struct {
	Cursor int64 `json:"cursor"`
	Ps     int64 `form:"ps,default=20"` // 每页大小
}

type CategoryListResponse struct {
	Products []*Product `json:"products"`
	IsEnd    bool       `json:"is_end"`
	LastVal  int64      `json:"last_val"`
}

type CartListRequest struct {
	UID int64 `form:"uid"`
}

type CartListResponse struct {
	Products []*Product `json:"product"`
	Count    int64      `json:"count"` // 购买数量
}

type ProductCommentRequest struct {
	ProductID int64 `form:"product_id"`
	Cursor    int64 `json:"cursor"`
	Ps        int64 `form:"ps,default=20"` // 每页大小
}

type ProductCommentResponse struct {
	Comments    []*Comment `json:"comments"`
	IsEnd       bool       `json:"is_end"`
	CommentTime int64      `json:"comment_time"`
}

type Comment struct {
	ID         int64    `json:"id"`          // 评论id
	ProductID  int64    `json:"product_id"`  // 商品id
	Content    string   `json:"content"`     // 评论内容
	Images     []*Image `json:"images"`      // 评论图片
	User       *User    `json:"user"`        // 用户信息
	CreateTime int64    `json:"create_time"` // 评论时间
	UpdateTime int64    `json:"update_time"` // 更新时间
}

type User struct {
	ID     int64  `json:"id"`     // 用户id
	Name   string `json:"name"`   // 用户名
	Avatar string `json:"avatar"` // 头像
}

type Image struct {
	ID  int64  `json:"id"`
	URL string `json:"url"`
}
